out_dir: results/enzyme
metric_best: accuracy
metric_agg: argmax
wandb:
  use: False
  project: enzyme-GPS
dataset:
  format: PyG-TUDataset
  name: ENZYMES # Correct format for enzyme dataset in PyG
  task: graph
  task_type: classification
  # name: ENZYMES  # Dataset name for ENZYMES in PyTorch Geometric
  transductive: False
  split_mode: random
  node_encoder: True # Use random embeddings for nodes
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False

posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none

train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  graph_pooling: mean
  # dim_hidden: 96
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 6
  n_heads: 4
  dim_hidden: 128
  dropout: 0.5
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1
  dim_inner: 128
  batchnorm: True
  act: relu
  dropout: 0.1

optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.01
  base_lr: 0.001
  max_epoch: 50
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
